services:
  server:
    image: joleaf/value-api-server
    ports:
      - 8081:8081
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8081

  frontend:
    image: joleaf/value-api-frontend
    ports: 
      - 8082:8082
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8082
      VALUE_API_SERVER: http://server:8081
      CONTEXT: local

