services:
  app:
    image: joleaf/value-api-server
    ports:
      - 8081:8081
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8081
